# Configuration for Alacritty, the GPU enhanced terminal emulator.

# Window opacity as a floating point number from `0.0` to `1.0`.
# The value `0.0` is completely transparent and `1.0` is opaque.
opacity: 0.0

# Live config reload (changes require restart)
live_config_reload: true

# This allows for mapping shift enter in nvim 
key_bindings:
  - { key: Return,   mods: Shift,   chars: "\x1b[13;2u" }
  - { key: Return,   mods: Control, chars: "\x1b[13;5u" }

hints:
  # First character in the hint label
  #
  # Allowed values are CellForeground/CellBackground, which reference the
  # affected cell, or hexadecimal colors like #ff00ff.
  start:
    foreground: '#1d1f21'
    background: '#e9ff5e'

  # All characters after the first one in the hint label
  #
  # Allowed values are CellForeground/CellBackground, which reference the
  # affected cell, or hexadecimal colors like #ff00ff.
  end:
    foreground: '#e9ff5e'
    background: '#1d1f21'

debug:
  # Display the time it takes to redraw each frame.
  render_timer: false

