# Configuration for Alacritty, the GPU enhanced terminal emulator.

window:
  # Window opacity as a floating point number from `0.0` to `1.0`.
  # The value `0.0` is completely transparent and `1.0` is opaque.
  opacity: 0.8

# Live config reload (changes require restart)
live_config_reload: true

# This allows for mapping shift enter in nvim
key_bindings:
  - { key: Return,   mods: Shift,   chars: "\x1b[13;2u" }
  - { key: Return,   mods: Control, chars: "\x1b[13;5u" }

# Font configuration (changes require restart)
font:
  # The normal (roman) font face to use.
  # Style can be specified to pick a specific face.
  normal:
    family: OpenDyslexicM Nerd Font Mono
    style: Light
    # family: "Fira Code"
    # family: "Source Code Pro"
    # style: Retina

  # The bold font face
  bold:
    family: OpenDyslexicM Nerd Font Mono
    style: Medium
    # family: "Fira Code"
    # family: "Source Code Pro"

  # The italic font face
  italic:
    family: OpenDyslexicM Nerd Font Mono
    style: "Light Italic"
    # style: "Light Oblique"
    # family: "Fira Code"
    # family: "Source Code Pro"
    # style: "Medium Italic"

  # Point size of the font
  size: 14.5

hints:
  # First character in the hint label
  #
  # Allowed values are CellForeground/CellBackground, which reference the
  # affected cell, or hexadecimal colors like #ff00ff.
  start:
    foreground: '#1d1f21'
    background: '#e9ff5e'

  # All characters after the first one in the hint label
  #
  # Allowed values are CellForeground/CellBackground, which reference the
  # affected cell, or hexadecimal colors like #ff00ff.
  end:
    foreground: '#e9ff5e'
    background: '#1d1f21'

debug:
  # Display the time it takes to redraw each frame.
  render_timer: false
